/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedEspaceRouteImport } from './routes/_authenticated/espace'
import { Route as AuthClientRouteImport } from './routes/auth/client'
import { Route as AuthPrestataireRouteImport } from './routes/auth/prestataire'
import { Route as PrestatairesIndexRouteImport } from './routes/prestataires.index'
import { Route as PrestatairesIdRouteImport } from './routes/prestataires.$id'
import { Route as AuthenticatedEspaceIndexRouteImport } from './routes/_authenticated/espace.index'
import { Route as AuthenticatedEspaceRechercheRouteImport } from './routes/_authenticated/espace.recherche'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEspaceRoute = AuthenticatedEspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthClientRoute = AuthClientRouteImport.update({
  id: '/auth/client',
  path: '/auth/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPrestataireRoute = AuthPrestataireRouteImport.update({
  id: '/auth/prestataire',
  path: '/auth/prestataire',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestatairesIndexRoute = PrestatairesIndexRouteImport.update({
  id: '/prestataires/',
  path: '/prestataires/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestatairesIdRoute = PrestatairesIdRouteImport.update({
  id: '/prestataires/$id',
  path: '/prestataires/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEspaceIndexRoute =
  AuthenticatedEspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceRechercheRoute =
  AuthenticatedEspaceRechercheRouteImport.update({
    id: '/recherche',
    path: '/recherche',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/espace': typeof AuthenticatedEspaceRouteWithChildren
  '/auth/client': typeof AuthClientRoute
  '/auth/prestataire': typeof AuthPrestataireRoute
  '/prestataires/$id': typeof PrestatairesIdRoute
  '/prestataires/': typeof PrestatairesIndexRoute
  '/espace/recherche': typeof AuthenticatedEspaceRechercheRoute
  '/espace/': typeof AuthenticatedEspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/client': typeof AuthClientRoute
  '/auth/prestataire': typeof AuthPrestataireRoute
  '/prestataires/$id': typeof PrestatairesIdRoute
  '/prestataires': typeof PrestatairesIndexRoute
  '/espace/recherche': typeof AuthenticatedEspaceRechercheRoute
  '/espace': typeof AuthenticatedEspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/espace': typeof AuthenticatedEspaceRouteWithChildren
  '/auth/client': typeof AuthClientRoute
  '/auth/prestataire': typeof AuthPrestataireRoute
  '/prestataires/$id': typeof PrestatairesIdRoute
  '/prestataires/': typeof PrestatairesIndexRoute
  '/_authenticated/espace/recherche': typeof AuthenticatedEspaceRechercheRoute
  '/_authenticated/espace/': typeof AuthenticatedEspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/espace'
    | '/auth/client'
    | '/auth/prestataire'
    | '/prestataires/$id'
    | '/prestataires/'
    | '/espace/recherche'
    | '/espace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/client'
    | '/auth/prestataire'
    | '/prestataires/$id'
    | '/prestataires'
    | '/espace/recherche'
    | '/espace'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/espace'
    | '/auth/client'
    | '/auth/prestataire'
    | '/prestataires/$id'
    | '/prestataires/'
    | '/_authenticated/espace/recherche'
    | '/_authenticated/espace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthClientRoute: typeof AuthClientRoute
  AuthPrestataireRoute: typeof AuthPrestataireRoute
  PrestatairesIdRoute: typeof PrestatairesIdRoute
  PrestatairesIndexRoute: typeof PrestatairesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/espace': {
      id: '/_authenticated/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof AuthenticatedEspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/client': {
      id: '/auth/client'
      path: '/auth/client'
      fullPath: '/auth/client'
      preLoaderRoute: typeof AuthClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/prestataire': {
      id: '/auth/prestataire'
      path: '/auth/prestataire'
      fullPath: '/auth/prestataire'
      preLoaderRoute: typeof AuthPrestataireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestataires/': {
      id: '/prestataires/'
      path: '/prestataires'
      fullPath: '/prestataires/'
      preLoaderRoute: typeof PrestatairesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestataires/$id': {
      id: '/prestataires/$id'
      path: '/prestataires/$id'
      fullPath: '/prestataires/$id'
      preLoaderRoute: typeof PrestatairesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/espace/': {
      id: '/_authenticated/espace/'
      path: '/'
      fullPath: '/espace/'
      preLoaderRoute: typeof AuthenticatedEspaceIndexRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/recherche': {
      id: '/_authenticated/espace/recherche'
      path: '/recherche'
      fullPath: '/espace/recherche'
      preLoaderRoute: typeof AuthenticatedEspaceRechercheRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
  }
}

interface AuthenticatedEspaceRouteChildren {
  AuthenticatedEspaceRechercheRoute: typeof AuthenticatedEspaceRechercheRoute
  AuthenticatedEspaceIndexRoute: typeof AuthenticatedEspaceIndexRoute
}

const AuthenticatedEspaceRouteChildren: AuthenticatedEspaceRouteChildren = {
  AuthenticatedEspaceRechercheRoute: AuthenticatedEspaceRechercheRoute,
  AuthenticatedEspaceIndexRoute: AuthenticatedEspaceIndexRoute,
}

const AuthenticatedEspaceRouteWithChildren =
  AuthenticatedEspaceRoute._addFileChildren(AuthenticatedEspaceRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEspaceRoute: typeof AuthenticatedEspaceRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEspaceRoute: AuthenticatedEspaceRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthClientRoute: AuthClientRoute,
  AuthPrestataireRoute: AuthPrestataireRoute,
  PrestatairesIdRoute: PrestatairesIdRoute,
  PrestatairesIndexRoute: PrestatairesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
